(******************************************************************************)
(*                                                                            *)
(*                  Anti-Money Laundering Transaction Rules                   *)
(*                                                                            *)
(*     Suspicious activity detection: structuring, rapid movement, layering,  *)
(*     and threshold reporting per FATF and FinCEN. Models the pattern-       *)
(*     matching logic that triggers Suspicious Activity Reports.              *)
(*                                                                            *)
(*     "Follow the money."                                                    *)
(*     – All the President's Men, 1976                                        *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 5, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
